// --- 1. DỮ LIỆU GIẢ LẬP (MOCK DATA) ---
export let mockData = [
  {
    id: 1,
    projectId: "project1",
    title: "Dự án Xây dựng Website",
    metaTitle: "Xây dựng Website - Trang web đẹp...",
    description: "Mô tả ngắn gọn về quá trình xây dựng...",
    hasContent: true,
    createdAt: "2026-04-01",
    status: "new",
    updatedAt: "05/04/2026",
  },
  {
    id: 2,
    projectId: "project2",
    title: "Dự án Tối ưu SEO",
    metaTitle: "SEO top 1 Google cam kết...",
    description: "Các bước chi tiết để thực hiện SEO...",
    hasContent: false,
    createdAt: "2026-03-10",
    status: "partial",
    updatedAt: "15/03/2026",
  },
  {
    id: 3,
    projectId: "project3",
    title: "Kế hoạch Marketing",
    metaTitle: "Kế hoạch Marketing Facebook ads...",
    description: "Dự trù kinh phí chạy quảng cáo cho năm nay...",
    hasContent: false,
    createdAt: "2026-02-20",
    status: "done",
    updatedAt: "01/03/2026",
  },
  {
    id: 4,
    projectId: "project1",
    title: "Dự án Xây dựng Website",
    metaTitle: "Xây dựng Website - Trang web đẹp...",
    description: "Mô tả ngắn gọn về quá trình xây dựng...",
    hasContent: false,
    createdAt: "2026-04-01",
    status: "done",
    updatedAt: "05/04/2026",
  },
  {
    id: 5,
    projectId: "project1",
    title: "Dự án Xây dựng Website",
    metaTitle: "Xây dựng Website - Trang web đẹp...",
    description: "Mô tả ngắn gọn về quá trình xây dựng...",
    hasContent: false,
    createdAt: "2026-04-01",
    status: "done",
    updatedAt: "05/04/2026",
  },
  {
    id: 6,
    projectId: "project1",
    title: "Dự án Xây dựng Website",
    metaTitle: "Xây dựng Website - Trang web đẹp...",
    description: "Mô tả ngắn gọn về quá trình xây dựng...",
    hasContent: false,
    createdAt: "2026-04-01",
    status: "done",
    updatedAt: "05/04/2026",
  },
  {
    id: 7,
    projectId: "project1",
    title: "Dự án Xây dựng Website",
    metaTitle: "Xây dựng Website - Trang web đẹp...",
    description: "Mô tả ngắn gọn về quá trình xây dựng...",
    hasContent: false,
    createdAt: "2026-04-01",
    status: "done",
    updatedAt: "05/04/2026",
  },
];
